version: '3.9'

# services we want to start
services:
  # Mongo DB service
  mongo_db:
    # any name to the container
    container_name: db_container
    # image to pull from docker hub
    image: mongo:latest
    # if container fails for some reason, then restart always
    restart: always
    # database files will be map in volumes
    volumes:
      - mongo_db:/data/db
  # NodeJS our api service
  api:
    container_name: school_node
    # pull docker file from root directory
    build: .
    ports:
      - 8080:8080
    # environment variables to run into the application
    environment:
      PORT: 8080
      MONGO_URL: mongodb://mongo_db:27017
      JWT_KEY: "uew9sdjs"
      JWT_KEY_DURATION: "1d"
      NODE_ENV: "dev"
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}