name: tests

on:
    pull_request

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Install dependencies and run tests
              run: npm ci && npm run test
#            - name: Build the Docker image
#              run: docker build -t generic-cart:${{ github.run_number }} --progress=plain --no-cache .
